name: "changesets Release"

on:
  pull_request_target:
    branches:
      - dev
      - master
    paths:
      - "**/CHANGELOG.md"
    types:
      - closed

jobs:
  unit-tests:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/reusable-unit-tests.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  api-library-tests:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/reusable-api-library-tests.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  # nextjs-app-setup:
  #   uses: ./.github/workflows/reusable-nextjs-app-setup.yml

  package-tests:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/reusable-package-tests.yml

  integration-tests-on-prem:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/reusable-integration-tests-on-prem.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  toolbox-tests:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/reusable-toolbox-tests.yml

  aura-free-tests:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/reusable-aura-tests.yml
    secrets:
      URI: ${{ secrets.AURA_FREE_URI }}
      PASSWORD: ${{ secrets.AURA_FREE_PASSWORD }}
    concurrency: aura-free

  aura-professional-tests:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/reusable-aura-tests.yml
    secrets:
      URI: ${{ secrets.AURA_PROFESSIONAL_URI }}
      PASSWORD: ${{ secrets.AURA_PROFESSIONAL_PASSWORD }}
    concurrency: aura-professional

  # slack-release-notification:
  #   needs:
  #     - bump-version

  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Send Slack notification of upcoming release
  #       id: slack-notification
  #       uses: slackapi/slack-github-action@v1.19.0
  #       with:
  #         payload: '{"version":"${{ needs.bump-version.outputs.version }}"}'
  #       env:
  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_RELEASE_NOTIFICATION_WEBHOOK_URL }}

  publish:
    if: github.event.pull_request.merged == true

    needs:
      - unit-tests
      - api-library-tests
      - package-tests
      - integration-tests-on-prem
      - toolbox-tests
      - aura-tests

    runs-on: ubuntu-latest

    environment:
      name: npm

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            @neo4j:registry https://registry.npmjs.org
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: changeset publish
        run: yarn changeset publish

  # slack-release-announcement:
  #   needs:
  #     - bump-version
  #     - changelog

  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Send Slack announcement of release
  #       id: slack-announcement
  #       uses: slackapi/slack-github-action@v1.19.0
  #       with:
  #         payload: '{"version":"${{ needs.bump-version.outputs.version }}"}'
  #       env:
  #         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_RELEASE_ANNOUNCEMENT_WEBHOOK_URL }}
